server {
    listen 80;

    location / {
        proxy_pass http://frontend:80;  # Forward root requests to the frontend
    }

    location /api {
        proxy_pass http://backend:3000;  # Forward API requests to the backend
    }
}
